"""empty message

Revision ID: 03f6c5edc2df
Revises: df639af6362a
Create Date: 2024-07-05 10:35:02.196566

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03f6c5edc2df"
down_revision = "df639af6362a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("idx_start", sa.Integer(), nullable=False),
        sa.Column("idx_end", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "page", name="uq_name_page"),
    )
    with op.batch_alter_table("dics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dics_idx_end"), ["idx_end"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dics_idx_start"), ["idx_start"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dics_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_dics_page"), ["page"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dics_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dics_time_updated"), ["time_updated"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dics_time_updated"))
        batch_op.drop_index(batch_op.f("ix_dics_time_created"))
        batch_op.drop_index(batch_op.f("ix_dics_page"))
        batch_op.drop_index(batch_op.f("ix_dics_name"))
        batch_op.drop_index(batch_op.f("ix_dics_idx_start"))
        batch_op.drop_index(batch_op.f("ix_dics_idx_end"))

    op.drop_table("dics")
    # ### end Alembic commands ###
