"""empty message

Revision ID: 125c089f9f62
Revises: 16ac4c4560c3
Create Date: 2024-06-05 17:41:57.484808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125c089f9f62'
down_revision = '16ac4c4560c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic', sa.String(length=16), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('idx_start', sa.Integer(), nullable=False),
    sa.Column('idx_end', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dic', 'page', name='uq_dic_page')
    )
    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionaries_dic'), ['dic'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionaries_idx_end'), ['idx_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionaries_idx_start'), ['idx_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionaries_page'), ['page'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionaries_time_created'), ['time_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionaries_time_updated'), ['time_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionaries_time_updated'))
        batch_op.drop_index(batch_op.f('ix_dictionaries_time_created'))
        batch_op.drop_index(batch_op.f('ix_dictionaries_page'))
        batch_op.drop_index(batch_op.f('ix_dictionaries_idx_start'))
        batch_op.drop_index(batch_op.f('ix_dictionaries_idx_end'))
        batch_op.drop_index(batch_op.f('ix_dictionaries_dic'))

    op.drop_table('dictionaries')
    # ### end Alembic commands ###
