"""empty message

Revision ID: 473c7448ea29
Revises: 03f6c5edc2df
Create Date: 2024-07-08 16:20:10.481315

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "473c7448ea29"
down_revision = "03f6c5edc2df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mnemonics", schema=None) as batch_op:
        batch_op.alter_column(
            "keyword", existing_type=sa.VARCHAR(length=64), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mnemonics", schema=None) as batch_op:
        batch_op.alter_column(
            "keyword", existing_type=sa.VARCHAR(length=64), nullable=False
        )

    # ### end Alembic commands ###
