"""empty message

Revision ID: 558f9517da08
Revises: 58b92e644987
Create Date: 2024-06-08 13:43:10.862169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558f9517da08'
down_revision = '58b92e644987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('meaning',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('meaning',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
