"""empty message

Revision ID: 8b9113afd64b
Revises: a649624f032c
Create Date: 2024-07-08 17:27:24.537142

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b9113afd64b"
down_revision = "a649624f032c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column(
            "my_keyword",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column(
            "my_keyword",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=32),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
