"""empty message

Revision ID: 9a99104a868a
Revises: 8b9113afd64b
Create Date: 2024-07-09 02:36:46.225946

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a99104a868a"
down_revision = "8b9113afd64b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kanjikirja", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_characters_kanjikirja"), ["kanjikirja"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_kanjikirja"))
        batch_op.drop_column("kanjikirja")

    # ### end Alembic commands ###
