"""empty message

Revision ID: a649624f032c
Revises: 473c7448ea29
Create Date: 2024-07-08 17:23:04.640902

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a649624f032c"
down_revision = "473c7448ea29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("my_keyword", sa.String(length=32), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_characters_my_keyword"), ["my_keyword"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_my_keyword"))
        batch_op.drop_column("my_keyword")

    # ### end Alembic commands ###
