"""empty message

Revision ID: ccf19812f563
Revises: 787a5a53eee5
Create Date: 2024-06-05 17:02:48.325300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf19812f563'
down_revision = '787a5a53eee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mnemonics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=32), nullable=False),
    sa.Column('story', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_literal', sa.String(length=1), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_literal'], ['characters.literal'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_literal', name='uq_user_character')
    )
    with op.batch_alter_table('mnemonics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mnemonics_time_created'), ['time_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_mnemonics_time_updated'), ['time_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mnemonics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mnemonics_time_updated'))
        batch_op.drop_index(batch_op.f('ix_mnemonics_time_created'))

    op.drop_table('mnemonics')
    # ### end Alembic commands ###
