"""empty message

Revision ID: df639af6362a
Revises: 
Create Date: 2024-07-04 15:03:53.129420

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df639af6362a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("literal", sa.String(length=1), nullable=False),
        sa.Column("ucs", sa.String(length=8), nullable=False),
        sa.Column("jis208", sa.String(length=8), nullable=True),
        sa.Column("jis212", sa.String(length=8), nullable=True),
        sa.Column("jis213", sa.String(length=8), nullable=True),
        sa.Column("radical", sa.String(length=1), nullable=False),
        sa.Column("stroke_count", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("freq", sa.Integer(), nullable=True),
        sa.Column("jlpt", sa.Integer(), nullable=True),
        sa.Column("nelson_c", sa.Integer(), nullable=True),
        sa.Column("nelson_n", sa.Integer(), nullable=True),
        sa.Column("heisig", sa.Integer(), nullable=True),
        sa.Column("heisig6", sa.Integer(), nullable=True),
        sa.Column("halpern_kkd", sa.Integer(), nullable=True),
        sa.Column("halpern_kkld_2ed", sa.Integer(), nullable=True),
        sa.Column("heisig_keyword", sa.String(length=32), nullable=True),
        sa.Column("parts", sa.String(length=32), nullable=True),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("literal"),
        sa.UniqueConstraint("jis208"),
        sa.UniqueConstraint("jis212"),
        sa.UniqueConstraint("jis213"),
        sa.UniqueConstraint("ucs"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_characters_halpern_kkd"), ["halpern_kkd"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_halpern_kkld_2ed"),
            ["halpern_kkld_2ed"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_characters_heisig"), ["heisig"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_heisig6"), ["heisig6"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_heisig_keyword"), ["heisig_keyword"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_nelson_c"), ["nelson_c"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_nelson_n"), ["nelson_n"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_parts"), ["parts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_characters_time_updated"), ["time_updated"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_password_hash"), ["password_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_users_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_time_updated"), ["time_updated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "decompositions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decomposition", sa.String(length=32), nullable=False),
        sa.Column("character_literal", sa.String(length=1), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_literal"],
            ["characters.literal"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decomposition", "character_literal", name="uq_decomposition_character"
        ),
    )
    with op.batch_alter_table("decompositions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decompositions_decomposition"),
            ["decomposition"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_decompositions_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decompositions_time_updated"), ["time_updated"], unique=False
        )

    op.create_table(
        "meanings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meaning", sa.String(length=128), nullable=False),
        sa.Column("character_literal", sa.String(length=1), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_literal"],
            ["characters.literal"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "meaning", "character_literal", name="uq_meaning_character"
        ),
    )
    with op.batch_alter_table("meanings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_meanings_meaning"), ["meaning"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_meanings_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_meanings_time_updated"), ["time_updated"], unique=False
        )

    op.create_table(
        "mnemonics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=64), nullable=False),
        sa.Column("story", sa.String(length=512), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("character_literal", sa.String(length=1), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_literal"],
            ["characters.literal"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "character_literal", name="uq_user_character"),
    )
    with op.batch_alter_table("mnemonics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mnemonics_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mnemonics_time_updated"), ["time_updated"], unique=False
        )

    op.create_table(
        "readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("r_type", sa.String(length=8), nullable=False),
        sa.Column("reading", sa.String(length=32), nullable=False),
        sa.Column("character_literal", sa.String(length=1), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_literal"],
            ["characters.literal"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "r_type", "reading", "character_literal", name="uq_type_reading_character"
        ),
    )
    with op.batch_alter_table("readings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_readings_r_type"), ["r_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_readings_reading"), ["reading"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_readings_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_readings_time_updated"), ["time_updated"], unique=False
        )

    op.create_table(
        "variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("var_type", sa.String(length=8), nullable=False),
        sa.Column("variant", sa.String(length=8), nullable=False),
        sa.Column("character_literal", sa.String(length=1), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_literal"],
            ["characters.literal"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "var_type", "variant", "character_literal", name="uq_type_variant_character"
        ),
    )
    with op.batch_alter_table("variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_variants_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_variants_time_updated"), ["time_updated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_variants_var_type"), ["var_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_variants_variant"), ["variant"], unique=False
        )

    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kanji", sa.String(length=32), nullable=False),
        sa.Column("kana", sa.String(length=32), nullable=False),
        sa.Column("meaning", sa.String(length=1024), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kanji", "kana", "user_id", name="uq_kanji_kana_user"),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_words_time_created"), ["time_created"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_words_time_updated"), ["time_updated"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_words_time_updated"))
        batch_op.drop_index(batch_op.f("ix_words_time_created"))

    op.drop_table("words")
    with op.batch_alter_table("variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_variants_variant"))
        batch_op.drop_index(batch_op.f("ix_variants_var_type"))
        batch_op.drop_index(batch_op.f("ix_variants_time_updated"))
        batch_op.drop_index(batch_op.f("ix_variants_time_created"))

    op.drop_table("variants")
    with op.batch_alter_table("readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readings_time_updated"))
        batch_op.drop_index(batch_op.f("ix_readings_time_created"))
        batch_op.drop_index(batch_op.f("ix_readings_reading"))
        batch_op.drop_index(batch_op.f("ix_readings_r_type"))

    op.drop_table("readings")
    with op.batch_alter_table("mnemonics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mnemonics_time_updated"))
        batch_op.drop_index(batch_op.f("ix_mnemonics_time_created"))

    op.drop_table("mnemonics")
    with op.batch_alter_table("meanings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meanings_time_updated"))
        batch_op.drop_index(batch_op.f("ix_meanings_time_created"))
        batch_op.drop_index(batch_op.f("ix_meanings_meaning"))

    op.drop_table("meanings")
    with op.batch_alter_table("decompositions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decompositions_time_updated"))
        batch_op.drop_index(batch_op.f("ix_decompositions_time_created"))
        batch_op.drop_index(batch_op.f("ix_decompositions_decomposition"))

    op.drop_table("decompositions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_time_updated"))
        batch_op.drop_index(batch_op.f("ix_users_time_created"))
        batch_op.drop_index(batch_op.f("ix_users_password_hash"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_time_updated"))
        batch_op.drop_index(batch_op.f("ix_characters_time_created"))
        batch_op.drop_index(batch_op.f("ix_characters_parts"))
        batch_op.drop_index(batch_op.f("ix_characters_nelson_n"))
        batch_op.drop_index(batch_op.f("ix_characters_nelson_c"))
        batch_op.drop_index(batch_op.f("ix_characters_heisig_keyword"))
        batch_op.drop_index(batch_op.f("ix_characters_heisig6"))
        batch_op.drop_index(batch_op.f("ix_characters_heisig"))
        batch_op.drop_index(batch_op.f("ix_characters_halpern_kkld_2ed"))
        batch_op.drop_index(batch_op.f("ix_characters_halpern_kkd"))

    op.drop_table("characters")
    # ### end Alembic commands ###
